# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

install! 'cocoapods', :disable_input_output_paths => true

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'isocietymanager' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

target 'OneSignalNotificationServiceExtension' do
  platform :ios, '13.0'

  pod 'OneSignal/OneSignal', '>= 5.2.9', '< 6.0'
end